name       : glibmm
version    : 2.54.1
release    : 13
source     :
    - http://ftp.acc.umu.se/pub/gnome/sources/glibmm/2.54/glibmm-2.54.1.tar.xz : 7cc28c732b04d70ed34f0c923543129083cfb90580ea4a2b4be5b38802bf6a4a
license    : GPL-2.0
component  : desktop.gnome.core
summary    : C++ bindings to GLib
description: |
    C++ bindings to GLib
builddeps  :
    - pkgconfig(sigc++-2.0)
patterns   :
    - docs :
        - /usr/share/devhelp
        - /usr/share/doc
    - devel :
        - /usr/lib/giomm-2.4
        - /usr/lib/glibmm-2.4
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
