name       : glibmm
version    : 2.56.0
release    : 14
source     :
    - https://download.gnome.org/sources/glibmm/2.56/glibmm-2.56.0.tar.xz : 6e74fcba0d245451c58fc8a196e9d103789bc510e1eee1a9b1e816c5209e79a9
license    : GPL-2.0-only
component  : desktop.gnome.core
summary    : C++ bindings to GLib
description: |
    C++ bindings to GLib
builddeps  :
    - pkgconfig(sigc++-2.0)
patterns   :
    - docs :
        - /usr/share/devhelp
        - /usr/share/doc
    - devel :
        - /usr/lib/giomm-2.4
        - /usr/lib/glibmm-2.4
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
