name       : glibmm
version    : 2.60.0
release    : 15
source     :
    - https://download.gnome.org/sources/glibmm/2.60/glibmm-2.60.0.tar.xz : a3a1b1c9805479a16c0018acd84b3bfff23a122aee9e3c5013bb81231aeef2bc
license    : GPL-2.0-only
component  : desktop.gnome.core
summary    : C++ bindings to GLib
description: |
    C++ bindings to GLib
builddeps  :
    - pkgconfig(sigc++-2.0)
patterns   :
    - docs :
        - /usr/share/devhelp
        - /usr/share/doc
    - devel :
        - /usr/lib/giomm-2.4
        - /usr/lib/glibmm-2.4
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
