name       : glibmm
version    : 2.51.6
release    : 10
source     :
    - http://ftp.acc.umu.se/pub/gnome/sources/glibmm/2.51/glibmm-2.51.6.tar.xz : bb7066781685853c006e6c164928d143dfa1adac4331caac2bf3d190b1ecc860
license    :
    - GPL-2.0
summary    : C++ bindings to GLib
builddeps  :
    - pkgconfig(sigc++-2.0)
component  : desktop.gnome.core
patterns   :
    - docs :
        - /usr/share/devhelp
        - /usr/share/doc
    - devel :
        - /usr/lib/giomm-2.4
        - /usr/lib/glibmm-2.4
description: |
    C++ bindings to GLib
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
