name       : glibmm
version    : 2.66.5
release    : 28
source     :
    - https://download.gnome.org/sources/glibmm/2.66/glibmm-2.66.5.tar.xz : 7b384662dd6ec3b86c0570331d32af05db2bd99a791602b767b4a0b2566ec149
license    : GPL-2.0-only
component  : desktop.gnome.core
summary    : C++ bindings to GLib
description: |
    C++ bindings to GLib
builddeps  :
    - pkgconfig(sigc++-2.0)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
