name       : glibmm
version    : 2.51.7
release    : 12
source     :
    - http://ftp.acc.umu.se/pub/gnome/sources/glibmm/2.51/glibmm-2.51.7.tar.xz : db67cc77f772fb8c727885b39ad6669ecb309cc72f7d76c25753a5c049dfb5f8
license    : GPL-2.0
component  : desktop.gnome.core
summary    : C++ bindings to GLib
description: |
    C++ bindings to GLib
builddeps  :
    - pkgconfig(sigc++-2.0)
patterns   :
    - docs :
        - /usr/share/devhelp
        - /usr/share/doc
    - devel :
        - /usr/lib/giomm-2.4
        - /usr/lib/glibmm-2.4
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
