name       : glibmm
version    : 2.64.5
release    : 24
source     :
    - https://download.gnome.org/sources/glibmm/2.64/glibmm-2.64.5.tar.xz : 508fc86e2c9141198aa16c225b16fd6b911917c0d3817602652844d0973ea386
license    : GPL-2.0-only
component  : desktop.gnome.core
summary    : C++ bindings to GLib
description: |
    C++ bindings to GLib
builddeps  :
    - pkgconfig(sigc++-2.0)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
