name       : glibmm
version    : 2.66.0
release    : 25
source     :
    - https://download.gnome.org/sources/glibmm/2.66/glibmm-2.66.0.tar.xz : 9e1db7d43d2e2d4dfa2771354e21a69a6beec7c446b711619cf8c779e13a581e
license    : GPL-2.0-only
component  : desktop.gnome.core
summary    : C++ bindings to GLib
description: |
    C++ bindings to GLib
builddeps  :
    - pkgconfig(sigc++-2.0)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
