name       : glibmm
version    : 2.50.0
release    : 9
source     :
    - http://ftp.acc.umu.se/pub/gnome/sources/glibmm/2.50/glibmm-2.50.0.tar.xz : df726e3c6ef42b7621474b03b644a2e40ec4eef94a1c5a932c1e740a78f95e94
license    :
    - GPL-2.0
summary    : C++ bindings to GLib
builddeps  :
    - pkgconfig(sigc++-2.0)
component  : desktop.gnome.core
patterns   :
    - docs :
        - /usr/share/devhelp
        - /usr/share/doc
    - devel :
        - /usr/lib/giomm-2.4
        - /usr/lib/glibmm-2.4
description: |
    C++ bindings to GLib
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
