name       : glibmm
version    : 2.62.0
release    : 17
source     :
    - https://download.gnome.org/sources/glibmm/2.62/glibmm-2.62.0.tar.xz : 36659f13cc73282392d1305858f3bbca46fbd1ce2f078cc9db8b9f79b2e93cfe
license    : GPL-2.0-only
component  : desktop.gnome.core
summary    : C++ bindings to GLib
description: |
    C++ bindings to GLib
builddeps  :
    - pkgconfig(sigc++-2.0)
patterns   :
    - docs :
        - /usr/share/devhelp
        - /usr/share/doc
    - devel :
        - /usr/lib/giomm-2.4
        - /usr/lib/glibmm-2.4
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
