name       : glibmm
version    : 2.66.6
release    : 29
source     :
    - https://download.gnome.org/sources/glibmm/2.66/glibmm-2.66.6.tar.xz : 5358742598181e5351d7bf8da072bf93e6dd5f178d27640d4e462bc8f14e152f
license    : GPL-2.0-only
component  : desktop.gnome.core
summary    : C++ bindings to GLib
description: |
    C++ bindings to GLib
builddeps  :
    - pkgconfig(sigc++-2.0)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
