name       : glibmm
version    : 2.64.0
release    : 20
source     :
    - https://download.gnome.org/sources/glibmm/2.64/glibmm-2.64.0.tar.xz : 46e83d4a123e41784b3b04a7cdcfcdaf918ba8e7e05b2acb10be0e0c09883c12
license    : GPL-2.0-only
component  : desktop.gnome.core
summary    : C++ bindings to GLib
description: |
    C++ bindings to GLib
builddeps  :
    - pkgconfig(sigc++-2.0)
patterns   :
    - docs :
        - /usr/share/devhelp
        - /usr/share/doc
    - devel :
        - /usr/lib/giomm-2.4
        - /usr/lib/glibmm-2.4
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
