name        : glibmm
version     : 2.44.0
release     : 6
source      :
    - http://ftp.gnome.org/pub/gnome/sources/glibmm/2.44/glibmm-2.44.0.tar.xz : 1b0ac0425d24895507c0e0e8088a464c7ae2d289c47afa1c11f63278fc672ea8
homepage    : http://www.gnome.org
license     :
    - GPL-2.0
summary     : C++ bindings to GLib
builddeps   :
    - pkgconfig(sigc++-2.0)
patterns    :
    - docs:
        - /usr/share/devhelp
        - /usr/share/doc
    - devel:
        - /usr/lib/giomm-2.4
        - /usr/lib/glibmm-2.4
description : |
    C++ bindings to GLib
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
