name       : glibmm
version    : 2.48.1
release    : 8
source     :
    - http://ftp.acc.umu.se/pub/gnome/sources/glibmm/2.48/glibmm-2.48.1.tar.xz : dc225f7d2f466479766332483ea78f82dc349d59399d30c00de50e5073157cdf
license    :
    - GPL-2.0
summary    : C++ bindings to GLib
builddeps  :
    - pkgconfig(sigc++-2.0)
patterns   :
    - docs :
        - /usr/share/devhelp
        - /usr/share/doc
    - devel :
        - /usr/lib/giomm-2.4
        - /usr/lib/glibmm-2.4
description: |
    C++ bindings to GLib
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
